# Generated by Django 4.0.4 on 2022-05-10 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='kudos_available',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
