# Generated by Django 4.0.4 on 2022-05-10 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_userdata_kudos_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='kudos_available',
            field=models.PositiveSmallIntegerField(default=3),
        ),
    ]
